### ISSUE TITLE
Player URL (for Twitter card) crash server

### ISSUE THREAD

**Issue by copernicus-mogley** [dloa/browser-react#19]
Player: static/img/SlackMarkBlack-Web-sm.png
/home/browser/browser-react/src/server.js:101
                                if (data[0]['media-data']) artifact = data[0]['media-data']['alexandria-media'];else //OIP
                                           ^

TypeError: Cannot read property 'media-data' of undefined
    at /home/browser/browser-react/src/server.js:77:9
    at Request._callback (/home/browser/browser-react/node_modules/libraryd-data/index.js:216:4)
    at Request.self.callback (/home/browser/browser-react/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/browser/browser-react/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/browser/browser-react/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)

**Comment by copernicus-mogley** [comment]
Solved here: https://github.com/dloa/browser-react/commit/22b713abacc436ec530f647bd886f6703fd5a479
